"""
AI Fault Diagnosis — Anomaly detection and fault classification.
Analyses telemetry data and system logs to identify, classify,
and correlate faults across vehicle subsystems.
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)


class FaultSeverity(str, Enum):
    """Fault severity classification."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class FaultCategory(str, Enum):
    """Fault category classification."""
    AERODYNAMICS = "aerodynamics"
    ENGINE = "engine"
    TRANSMISSION = "transmission"
    SUSPENSION = "suspension"
    BRAKES = "brakes"
    ELECTRONICS = "electronics"
    TYRES = "tyres"
    UNKNOWN = "unknown"


@dataclass
class FaultReport:
    """Structured fault report generated by the diagnosis engine."""
    fault_id: str
    vehicle_id: str
    session_id: str
    timestamp: datetime
    severity: FaultSeverity
    category: FaultCategory
    description: str
    affected_channels: list[str]
    anomaly_scores: dict[str, float]
    recommended_actions: list[str] = field(default_factory=list)
    root_cause: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "fault_id": self.fault_id,
            "vehicle_id": self.vehicle_id,
            "session_id": self.session_id,
            "timestamp": self.timestamp.isoformat(),
            "severity": self.severity.value,
            "category": self.category.value,
            "description": self.description,
            "affected_channels": self.affected_channels,
            "anomaly_scores": self.anomaly_scores,
            "recommended_actions": self.recommended_actions,
            "root_cause": self.root_cause,
        }


class FaultDiagnosisEngine:
    """
    Multi-signal fault diagnosis engine for racing vehicle telemetry.

    Integrates GRU anomaly scores, threshold-based rules, and cross-channel
    correlation to produce structured fault reports.
    """

    # Threshold rules per channel
    THRESHOLDS: dict[str, dict[str, float]] = {
        "oil_temp_c": {"high": 130.0, "critical": 145.0},
        "water_temp_c": {"high": 105.0, "critical": 115.0},
        "brake_temp_c": {"high": 700.0, "critical": 800.0},
        "tyre_temp_fl_c": {"high": 110.0, "critical": 120.0},
        "tyre_temp_fr_c": {"high": 110.0, "critical": 120.0},
        "tyre_temp_rl_c": {"high": 110.0, "critical": 120.0},
        "tyre_temp_rr_c": {"high": 110.0, "critical": 120.0},
        "rpm": {"high": 13500.0, "critical": 14000.0},
    }

    CHANNEL_CATEGORY_MAP: dict[str, FaultCategory] = {
        "oil_temp_c": FaultCategory.ENGINE,
        "water_temp_c": FaultCategory.ENGINE,
        "rpm": FaultCategory.ENGINE,
        "brake_temp_c": FaultCategory.BRAKES,
        "tyre_temp_fl_c": FaultCategory.TYRES,
        "tyre_temp_fr_c": FaultCategory.TYRES,
        "tyre_temp_rl_c": FaultCategory.TYRES,
        "tyre_temp_rr_c": FaultCategory.TYRES,
        "downforce_n": FaultCategory.AERODYNAMICS,
        "drag_n": FaultCategory.AERODYNAMICS,
    }

    def __init__(self) -> None:
        self._fault_counter = 0

    def _next_fault_id(self) -> str:
        self._fault_counter += 1
        return f"FAULT-{self._fault_counter:06d}"

    def diagnose(self, telemetry: dict[str, float],
                 vehicle_id: str, session_id: str,
                 gru_scores: dict[str, float] | None = None) -> list[FaultReport]:
        """
        Analyse telemetry snapshot and GRU scores to produce fault reports.

        Args:
            telemetry: Current telemetry channel values.
            vehicle_id: Vehicle identifier.
            session_id: Session identifier.
            gru_scores: Optional per-channel anomaly scores from GRU model.

        Returns:
            List of detected fault reports.
        """
        faults: list[FaultReport] = []
        ts = datetime.now(tz=timezone.utc)

        for channel, value in telemetry.items():
            if channel not in self.THRESHOLDS:
                continue
            thresholds = self.THRESHOLDS[channel]
            gru_score = (gru_scores or {}).get(channel, 0.0)

            severity = None
            if value >= thresholds.get("critical", float("inf")):
                severity = FaultSeverity.CRITICAL
            elif value >= thresholds.get("high", float("inf")):
                severity = FaultSeverity.HIGH
            elif gru_score > 0.7:
                severity = FaultSeverity.MEDIUM

            if severity is not None:
                category = self.CHANNEL_CATEGORY_MAP.get(channel, FaultCategory.UNKNOWN)
                faults.append(FaultReport(
                    fault_id=self._next_fault_id(),
                    vehicle_id=vehicle_id,
                    session_id=session_id,
                    timestamp=ts,
                    severity=severity,
                    category=category,
                    description=f"Anomaly detected on channel '{channel}': value={value:.2f}",
                    affected_channels=[channel],
                    anomaly_scores={channel: gru_score},
                    recommended_actions=self._recommend(channel, severity),
                ))

        if faults:
            logger.warning("Diagnosed %d fault(s) for vehicle %s", len(faults), vehicle_id)
        return faults

    def _recommend(self, channel: str, severity: FaultSeverity) -> list[str]:
        """Generate recommended actions for a fault."""
        recommendations: dict[str, list[str]] = {
            "oil_temp_c": ["Check oil cooler flow", "Reduce engine load", "Pit immediately if critical"],
            "water_temp_c": ["Check coolant level", "Check radiator", "Pit for inspection"],
            "brake_temp_c": ["Allow brakes to cool", "Adjust brake bias", "Check brake duct settings"],
            "rpm": ["Reduce engine RPM", "Check rev limiter settings", "Monitor engine telemetry"],
        }
        base = recommendations.get(channel, ["Monitor channel closely", "Contact race engineer"])
        if severity == FaultSeverity.CRITICAL:
            base.append("URGENT: Consider immediate pit stop")
        return base
